---
- name: Replace Cisco IOS-XE Router Configurations
  connection: local
  hosts: cisco-ios-xe-routers
  gather_facts: no
  vars:
    creds:
      hostname: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      dev_os: "{{ device_type }}"
  tags: ios-xe
  tasks:
    - napalm_install_config:
        provider: "{{ creds }}"
        config_file: "{{ lookup('pipe', 'ls -1 backup/{{ inventory_hostname }}_config.**') }}"
        commit_changes: True
        replace_config: True
- name: Replace Cisco NXOS Configurations
  connection: local
  hosts: cisco-nxos
  gather_facts: no
  vars:
    nxos_rollback_creds:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: "cli"
  tags: nxos
  tasks:
    - nxos_rollback:
        provider: "{{ nxos_rollback_creds }}"
        rollback_to: my_net_as_code_checkpoint
- name: Replace Cisco ASA Configurations
  connection: local
  hosts: cisco-asa
  gather_facts: no
  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      authorize: yes
      auth_pass: "{{ enable_password }}"
  tags: asa
  tasks:
    - shell: "{{ playbook_dir }}/asa_scp.py {{ ansible_host }} {{ username }} {{ password }} {{ enable_password }} {{ lookup('pipe', 'ls -1 backup/{{ inventory_hostname }}_config.**') }}"
    - asa_config:
        provider: "{{ creds }}"
        lines:
          - copy /noconfirm disk0:/backup.cfg startup-config
    - asa_command:
        provider: "{{ creds }}"
        commands:
          - reload noconfirm

